server:
  port: 8080
  address: 0.0.0.0
  compression:
    enabled: true
  tomcat:
    max-swallow-size: -1

spring:
  application:
    name: cloudpivot-web-api
  profiles:
    active: local

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cache:
    type: redis

  redis:
    host: 127.0.0.1
    database: 1
    password: foobared
    port: 6379

  mvc:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false
    check-template: false

  mobile:
    devicedelegatingviewresolver:
      enabled: true
      mobile-prefix: mobile/

  security:
    oauth:
      sso_uri: http://127.0.0.1:8080
      #      sso_uri: http://0.0.0.0:8888
      client_id: api
      client_secret: c31b32364ce19ca8fcd150a417ecce58
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB         #上传单个文件大小限制
      max-request-size: 200MB     #多个同时上传总大小限制

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.boot: error
    org.springframework.security.oauth2: error
    com.alibaba.dubbo: error
    com.authine.cloudpivot: debug
# 日志输出路径
log:
  path: portal-logs

dubbo:
  application:
    name: cloudpivot-web-api-consumer
    qos-enable: false
  registry:
    protocol: zookeeper
    address: 120.79.187.180
    #    address: 192.168.8.182
    port: 2181
    timeout: 3000
    check: true
  consumer:
    check: false
  provider:
    token: h3bpmtoken

cloudpivot:
  api:
    oauth:
      enabled: false  # 是否开启权限校验
      test:
        userid: 2c9280a26706a73a016706a93ccf002b  # 模拟测试用户ID，不能用于生产环境
    log:
      enabled: false #是否开启webapi请求记录生成
  dingtalk:
    client:
      aes_key: e6e18d0a42dd027cade89c213c75f477e6e18d0a42d
      aes_token: 2cc69a199b644f9ca0d21360f242d98d
      callback_tag:
        user_add_org,
        user_modify_org,
        user_leave_org,
        org_admin_add,
        org_admin_remove,
        org_dept_create,
        org_dept_modify,
        org_dept_remove,
        org_remove,
        org_change,
        label_user_change,
        label_conf_add,
        label_conf_del,
        label_conf_modify
      callback_url: /public/dingtalk/notify

aliyun:
  access:
    key_id: LTAIHGUm8FciwU0h
    key_secret: TkjCX6iVfxkm3FwTtMzMN795lO74Qn
  gts:
    vgroup: txc_demo.1147712096300880.SZ
  oss:
    ram:
      role:
        arn: acs:ram::1707221459317306:role/aliyunosstokengeneratorrole
        session_name: external-username
      duration_seconds: 3600
      policy_file: oss-all_policy.txt
    domain: h3yunuat.oss-cn-shenzhen.aliyuncs.com

#    文件上传配置已改为从数据库获取
#      access:
#        key_id: LTAIpjZgtclg0pxI
#        key_secret: S0qxf2oxKpA6JXfKNtMjTt8KBCOyMS
#    endpoint: oss-cn-shenzhen.aliyuncs.com
#    bucket: h3yunuat
#    token_expire_time: 7200